[package]
name = "midi-types"
version = "0.1.1"
edition = "2018"
rust-version = "1.32"

authors = ["Mendelt Siebenga <msiebenga@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Types for representing midi messages"
repository = "https://github.com/mendelt/midi-types"
categories = ["no-std", "api-bindings", "multimedia::audio"]
keywords = ["midi"]
readme = "README.md"

[dependencies]
